name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore "Planeja+.slnx"

      - name: Build
        run: dotnet build "Planeja+.slnx" --no-restore -c Release

      - name: Publish
        run: dotnet publish "Planeja+.Web/Planeja+.Web.csproj" --no-restore -c Release -o ./publish
